### ISSUE TITLE
Just get a spinner

### ISSUE THREAD

**Issue by scrop** [DrGoldfire/portland-transit-tracker-fitbit#1] opened 2018-06-11 21:30 UTC
Hi Matt. I loaded your app a couple days ago and added 2 bus lines and stops. When I start the app, though, I just get a spinner. I stopped waiting after 30 seconds. 

Great idea, I hope it can get fixed.

**Comment by DrGoldfire** [comment] 2018-06-12 14:10
Hmm, sorry about that. Have you tried restarting your watch? I know, I know, but I've seen this happen myself once and the cause was that the watch and the phone (which is responsible for making all the web requests) were somehow not fully connected even though they thought they were, and rebooting the watch fixed that for me.

**Comment by scrop** [comment] 2018-06-12 22:57
Thanks for the suggestion Matt.  I've rebooted the watch, rebooted the iPhone, removed and re-installed the app.  All with the same result.

**Comment by DrGoldfire** [comment] 2018-06-13 03:29
Okay, thanks for trying. I'm away all this week so there isn't much I can do right now, but when I get a chance I'll see about building a version with some diagnostics, to try and figure out what's going on.

Also, are you using an Ionic or a Versa? I only have a Versa, and in the simulator version of the Ionic everything does work, but it's always possible that there's some problem on the hardware that the simulator doesn't reflect.

**Comment by scrop** [comment] 2018-06-13 13:51
I have a versa connection to an iPhone 8 plus.  No rush.

**Comment by thumb** [comment] 2018-06-21 05:31
I'll add to scrop's report-- I get the same thing. If I update the info in the app settings screen in Fitbit with the transit app open on my watch, it refreshes and works. But closing and reopening the app gets it back to the wheel.

**Comment by scrop** [comment] 2018-06-22 16:04
Sure DrGoldfire, I can load up the dev tools.  I presume that I need to get signed up as a developer to do that, so I'll do that today.

**Comment by vpitoscia** [comment] 2019-04-23 22:27
After hitting what I thought was the same issue, I ran through some tests and can reproduce at least a version of this 100% of the time now. If you add two different lines, but the same stop, the app will be a perpetual spinner. In my scenario, I was adding both the Red and Blue lines, from the same stop, as these are interchangeable for my purposes. Things are fine with only one of them added, but when both are added the issue arises. 

Just got my watch, so I'll fire up the dev tools and see if I can't debug further when I get some time.

**Comment by vpitoscia** [comment] 2019-04-23 23:18
Looks like my repro steps were a complete red herring: 

[4:13:53 PM]error: RangeError: Encoded data too large: 1165 bytes
companion/index.js:33,5

**Comment by vpitoscia** [comment] 2019-04-23 23:37
Looks like the options are chunking, or using the file transfer API and reworking the app to watch for and parse the file.

**Comment by DrGoldfire** [comment] 2019-04-24 00:30
1027 bytes, huh. Would love to know what drove that particular limit. All right, I'll look into the file transfer API (not sure if that even existed when I wrote this thing, I don't remember it at all).

Thanks very much for the diagnosis/debugging effort, by the way; I don't know if the issue of hitting that limit would ever have occurred to me.

**Closed** 2019-04-24 02:08 UTC

**Comment by DrGoldfire** [comment] 2019-04-24 02:15
I've submitted an update with this patch for review; in the past that process has taken about three days.

**Comment by vpitoscia** [comment] 2019-04-24 03:07
Happy to help - Looking forward to getting the update once FitBit's approved it. Thanks!

**Comment by DrGoldfire** [comment] 2019-04-30 14:42
My update's been approved and I've just set it live. Thanks again for all the help!

**Comment by scrop** [comment] 2019-05-15 23:03
It works great! thanks @DrGoldfire for fixing it and @vpitoscia for helping!

**Comment by scrop** [comment] 2019-05-15 23:04
PS, I had to uninstall it and re-install it to get the update.

**Comment by DrGoldfire** [comment] 2019-05-15 23:16
I don’t think there’s anything I can do to have any effect on that update issue, the deployment tools available to developers are... not exactly robust. Thanks for letting me know, though.
